version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=prhq
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./packages/api
    volumes:
      - ./packages:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=prhq
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - WAIT_HOSTS=postgres:5432
    ports:
      - '3050:5000'