version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prhq
  api:
    depends_on:
      - postgres
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./packages/api
    volumes:
      - ./packages:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=prhq
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - '3050:5000'